apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
  namespace: map-app
spec:
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: LoadBalancer
