apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: map-app
spec:
  selector:
    app: map-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
