version: '3.1'

services:
  mysql:
    container_name: db-container
    build:
      dockerfile: ./mysql/Dockerfile
    image: "map-app-db"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      BIND-ADDRESS: 0.0.0.0
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306