apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  namespace: map-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app-container
          image: sham6/map-app-spring:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: datasourceurl
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: dbuser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: dbpassword
